site_name: My Documentation
site_description: A documentation site built with MkDocs Material
site_url: https://example.com
repo_url: https://github.com/taubyte/tau
repo_name: taubyte/tau
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  palette:
    # Palette toggle for dark mode (default)
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      type: date

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/taubyte/tau
      name: GitHub Repository
    - icon: fontawesome/solid/star
      link: https://github.com/taubyte/tau/stargazers
      name: GitHub Stars

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference: api.md
